Sort imports
yaptide/ui pull request #1093
Opened 2023-06-19 18:35 UTC by ostatni5

2023-06-20 06:26 UTC, grzanka commented
@ostatni5 will this work with husky ?

2023-06-20 12:23 UTC, Derstilon requested changes
Update lint-staged config in package json to include autofix on comitted files

2023-06-20 15:59 UTC, ostatni5 commented on package.json
> +			"sort-imports-es6-autofix"
Seems legit

2023-06-20 17:22 UTC, grzanka commented
![image](https://github.com/yaptide/ui/assets/7374733/7e21ece7-c4d3-45a4-8a4e-8a658323704b)

tests are failing

2023-06-21 17:26 UTC, Derstilon approved these changes

2023-06-21 17:26 UTC, merged