Fix button functionality on simulation card
yaptide/ui pull request #1172
Opened 2023-09-01 13:20 UTC by Derstilon

Closes #1168 
![image](https://github.com/yaptide/ui/assets/26445545/46532c59-2402-44fb-b27e-8bfb67fc370a)
![image](https://github.com/yaptide/ui/assets/26445545/856754b0-cb3a-4207-a3a0-ac335a7d8af8)
![image](https://github.com/yaptide/ui/assets/26445545/7d0c70a5-3e97-4729-9386-581a55dd1fb2)

2023-09-01 20:00 UTC, grzanka commented
In principle it works, but there is also a checkbox "Include simulation results" which has no effect.
Whether being checked or not, simulation results are being added to the JSON.
![image](https://github.com/yaptide/ui/assets/7374733/32360f15-366c-4b18-8439-50a2206fe36b)

2023-09-01 20:00 UTC, grzanka requested changes
If that is not massive amount of the work, fix the checkbox selecting whether to save results or not. If the work is massive, then remove that checkbox and always save the results

2023-09-02 21:09 UTC, ostatni5 submitted a review, later dismissed

2023-09-04 17:36 UTC, grzanka approved these changes

2023-09-04 18:15 UTC, ostatni5 approved these changes

2023-09-04 18:42 UTC, merged