1280 unhandled keycloak log in failure
yaptide/ui pull request #1288
Opened 2023-10-18 17:38 UTC by Derstilon

- [X] https://github.com/yaptide/ui/issues/1280
- [ ] https://github.com/yaptide/ui/issues/1282
- [X] https://github.com/yaptide/ui/issues/1127

2023-10-19 20:17 UTC, grzanka commented
Still when trying to run a simulation locally I get:
![image](https://github.com/yaptide/ui/assets/7374733/364cec06-b43b-49a1-88d0-c9d4484c42ed)

2023-10-20 07:12 UTC, grzanka commented
@Derstilon tests are failing now

![image](https://github.com/yaptide/ui/assets/7374733/c56b652e-a6fc-4a99-8ef2-953d36de2a4b)

2023-10-20 07:18 UTC, grzanka commented
I am able to run simulations now, it seems that just the tests needs to be fixed

2023-10-20 18:05 UTC, grzanka commented
@Derstilon can you fix the conflicts as well ?

2023-10-23 17:33 UTC, ostatni5 requested changes

2023-10-23 17:33 UTC, ostatni5 commented on src/ThreeEditor/js/Storage.js
> +			}
Examine if `try/catch` is needed.

2023-10-23 17:33 UTC, ostatni5 commented on src/ThreeEditor/js/Storage.js
> +			}
Examine if `try/catch` is needed.

2023-10-23 17:33 UTC, ostatni5 commented on src/WrapperApp/components/Simulation/SimulationCard.tsx
> +							!Boolean(
**nitpick:** You can probably remove the Boolean keyword

2023-10-23 17:33 UTC, ostatni5 commented on src/WrapperApp/components/Simulation/SimulationCardGrid.tsx
> +					disabled={!Boolean(isBackendAlive && yaptideEditor)}
Boolean

2023-10-23 17:33 UTC, ostatni5 commented on src/services/AuthService.tsx
>  		else if (!isServerReachable || !user?.source) setRefreshInterval(undefined);
If can be omitted

2023-10-23 17:33 UTC, ostatni5 commented on src/services/AuthService.tsx
>  			});
Add resolve/reject

2023-10-23 17:33 UTC, ostatni5 commented on src/services/AuthService.tsx
>  	const tokenVerification = useCallback(() => {
check if you must return smth

2023-10-23 17:33 UTC, ostatni5 commented on src/services/KeycloakAuthService.tsx
> +				value={{
extract to var

2023-10-25 14:36 UTC, grzanka commented
Logging works , the too frequent calls to keycloak disappeared

2023-10-25 14:37 UTC, grzanka commented
I have issues with submitting simulations to batch, 
this is an error from backend
```
INFO:werkzeug:172.18.0.5 - - [25/Oct/2023 14:34:13] "POST /jobs/batch HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/app/yaptide/routes/utils/decorators.py", line 24, in wrapper
    return f(user, *args, **kwargs)
  File "/usr/local/app/yaptide/routes/batch_routes.py", line 78, in post
    result = submit_job(payload_dict=payload_dict, files_dict=input_dict["input_files"], user=user,
  File "/usr/local/app/yaptide/batch/batch_methods.py", line 77, in submit_job
    array_id = int(line.split()[-1])
ValueError: invalid literal for int() with base 10: 'id:'
```

this is JSON send by frontend:
```
{"input_json":{"metadata":{"version":"0.11","type":"Editor","generator":"YaptideEditor.toJSON"},"project":{"title":"Proton pencil beam in water","description":"Proton pencil beam with initial kinetic energy 150 MeV and 1% energy spread.\nThe target is a cylindrical water phantom with a radius of 10 cm and a length of 20 cm.\n\nWe score dose from all particles and fluence according to primary particles (protons), secondary protons, and all protons.","viewManager":{"ViewPanelXY":{"cameraMatrix":[1,0,0,0,0,0.9999999999994964,9.999999999621397e-7,0,0,-9.999999999621397e-7,0.9999999999994964,0,0,-0.00009999999999621423,99.99999999994992,1],"clipPlane":{"planeConstant":0,"visible":true}},"ViewPanel3D":{"cameraMatrix":[0.7071067811865477,5.5511151231257815e-17,-0.707106781186547,0,-0.4082482904638628,0.8164965809277258,-0.4082482904638629,0,0.5773502691896248,0.5773502691896252,0.5773502691896255,0,10,10,10.000000000000002,1]},"ViewPanelY":{"cameraMatrix":[5.551115123125587e-16,-4.4408920985004704e-16,0.9999999999999649,0,0.9999999999994634,9.999999996956521e-7,-6.661338147750695e-16,0,-9.999999998066744e-7,0.9999999999994634,3.3306690738753473e-16,0,-0.00009999999999998334,99.99999999994999,6.1232339957357454e-21,1],"clipPlane":{"planeConstant":0,"visible":true}},"ViewPanelX":{"cameraMatrix":[1.1102230246251573e-16,1.0000000000000007,2.2204460492503146e-16,0,9.999999995846643e-7,-4.4408920985006163e-16,0.9999999999994978,0,0.9999999999994978,-2.2204460492503082e-16,-9.999999996956866e-7,0,99.99999999994995,0,-0.0000999999999999833,1],"clipPlane":{"planeConstant":0,"visible":true}},"ViewPanel":{"cameraMatrix":[0.07426714888874009,0,0.9972383820310657,0,0.1890359579236641,0.9818692455756362,-0.014078039800121761,0,-0.9791576978239105,0.18955944870338465,0.07292062945044075,0,-27.694761919291807,5.361550864645869,2.0625068629119263,1]}},"history":{"undos":[],"redos":[]}},"figureManager":{"uuid":"0F0F0F0F-0F0F-0F0F-0F0F-0F0F0F0F0F0F","name":"Figure Manager","type":"FigureManager","metadata":{"version":"0.11","type":"Manager","generator":"FigureManager.toJSON"},"figures":[{"name":"Water_phantom_cylinder","type":"CylinderFigure","uuid":"7ab62ba9-6dba-4543-b50b-ce31e143d482","visible":false,"geometryData":{"geometryType":"HollowCylinderGeometry","position":[0,0,10],"rotation":[0,0,0],"parameters":{"innerRadius":0,"radius":5,"depth":20}},"colorHex":0},{"name":"Vacuum_cylinder","type":"CylinderFigure","uuid":"aeeffad9-ed86-44ae-bfe4-b5f78580741b","visible":false,"geometryData":{"geometryType":"HollowCylinderGeometry","position":[0,0,10.5],"rotation":[0,0,0],"parameters":{"innerRadius":0,"radius":5.5,"depth":22}},"colorHex":0}]},"zoneManager":{"uuid":"368269D3-6F9B-4241-84A0-5D908D10E196","name":"Zones","type":"ZoneManager","metadata":{"version":"0.11","type":"Manager","generator":"ZoneManager.toJSON"},"zones":[{"uuid":"9ee041c1-acc0-433f-bc66-90e057b72474","name":"Water_phantom_zone","type":"BooleanZone","visible":true,"materialUuid":"49ce56b9-ee48-4640-88d4-bcfd660d8c0e","materialPropertiesOverrides":{},"unionOperations":[[{"mode":"union","objectUuid":"7ab62ba9-6dba-4543-b50b-ce31e143d482"}]],"subscribedObjects":{"7ab62ba9-6dba-4543-b50b-ce31e143d482":1}},{"uuid":"a2c614cf-7074-4abe-a757-4a850f6731b3","name":"Vacuum_zone","type":"BooleanZone","visible":true,"materialUuid":"cd7c2eb0-e91f-4144-b4eb-536e4626cc09","materialPropertiesOverrides":{},"unionOperations":[[{"mode":"union","objectUuid":"aeeffad9-ed86-44ae-bfe4-b5f78580741b"},{"mode":"subtraction","objectUuid":"7ab62ba9-6dba-4543-b50b-ce31e143d482"}]],"subscribedObjects":{"7ab62ba9-6dba-4543-b50b-ce31e143d482":1,"aeeffad9-ed86-44ae-bfe4-b5f78580741b":1}}],"worldZone":{"uuid":"73e69243-fc89-4f8f-b353-466e9d3921df","type":"WorldZone","name":"World Zone","marginMultiplier":1.1,"autoCalculate":false,"materialUuid":"1dd2e8f0-6684-42c2-ad35-7aa55358204e","visible":false,"geometryData":{"geometryType":"HollowCylinderGeometry","position":[0,0,10.5],"rotation":[0,0,0],"parameters":{"innerRadius":6,"radius":6,"depth":24}}}},"detectorManager":{"uuid":"9A7D17B8-BAE4-441F-965F-490CAA617EC6","name":"DetectManager","type":"DetectorManager","metadata":{"version":"0.11","type":"Manager","generator":"DetectorManager.toJSON"},"detectors":[{"name":"CylZ_Mesh","type":"Detector","uuid":"186ec65a-8511-418b-8218-8890138c6b12","visible":true,"colorHex":327424,"geometryData":{"geometryType":"Cyl","position":[0,0,10],"rotation":[0,0,0],"parameters":{"radius":5,"innerRadius":0,"depth":20,"radialSegments":1,"zSegments":400}}},{"name":"YZ_Mesh","type":"Detector","uuid":"3306e98b-5da2-46ee-8892-ac0191d645a7","visible":true,"colorHex":65535,"geometryData":{"geometryType":"Mesh","position":[0,0,10],"rotation":[0,0,0],"parameters":{"width":0.5,"height":4,"depth":20,"xSegments":1,"ySegments":80,"zSegments":400}}},{"name":"EntrySlab","type":"Detector","uuid":"53fff3c4-30de-4210-9066-20dc0f90cccb","visible":true,"colorHex":65535,"geometryData":{"geometryType":"Cyl","position":[0,0,0.05],"rotation":[0,0,0],"parameters":{"radius":5,"innerRadius":0,"depth":0.1,"radialSegments":1,"zSegments":1}}},{"name":"PeakSlab","type":"Detector","uuid":"deb6a8f8-fab3-488e-8a01-9bb3e8ea4649","visible":true,"colorHex":65535,"geometryData":{"geometryType":"Cyl","position":[0,0,15.35],"rotation":[0,0,0],"parameters":{"radius":5,"innerRadius":0,"depth":0.1,"radialSegments":1,"zSegments":1}}}]},"specialComponentsManager":{"uuid":"0F0F0F0F-0F0F-0F0F-0F0F-0F0F0F0F0FFF","name":"Special Components","type":"SpecialComponentManager","metadata":{"version":"0.11","type":"Manager","generator":"SpecialComponentManager.toJSON"}},"materialManager":{"uuid":"0F0F0F0F-0F0F-0F0F-0F0F-0F0F0FFFFFFF","name":"Material Manager","type":"MaterialManager","materials":[{"uuid":"1dd2e8f0-6684-42c2-ad35 [...]

2023-10-30 07:32 UTC, ostatni5 approved these changes

2023-10-30 08:18 UTC, grzanka approved these changes

2023-10-30 08:19 UTC, merged