Resolves 1287 Enable fluka simulation selection
yaptide/ui pull request #1289
Opened 2023-10-18 20:52 UTC by hendzeld

Add simulator selection before run

Resolves #1287

2023-10-19 20:07 UTC, grzanka commented on src/WrapperApp/components/Simulation/RunSimulationForm.tsx
> +							<MenuItem value={SimulatorType.TOPAS}>topas</MenuItem>
```suggestion
```

as for now we have no plans to add topas

2023-10-19 20:07 UTC, grzanka commented on src/WrapperApp/components/Simulation/RunSimulationForm.tsx
> +							<MenuItem value={SimulatorType.FLUKA}>fluka</MenuItem>
```suggestion
							<MenuItem value={SimulatorType.SHIELDHIT}>SHIELD-HIT12A</MenuItem>
							<MenuItem value={SimulatorType.FLUKA}>Fluka</MenuItem>
```

2023-10-19 20:08 UTC, grzanka requested changes
see comments

2023-10-20 15:58 UTC, grzanka approved these changes

2023-10-20 16:22 UTC, Derstilon commented on src/WrapperApp/components/Simulation/RunSimulationForm.tsx
> +					</FormControl>
It would be useful to lock this form control when we have forwardedSimulator defined and simulationSourceType is set to 'files'

2023-10-20 16:28 UTC, Derstilon approved these changes

2023-10-20 16:28 UTC, merged