Feature/205 auth
yaptide/ui pull request #282
Opened 2021-11-23 18:13 UTC by ostatni5

close #205

2021-11-26 17:01 UTC, Derstilon requested changes
I have few questions you can find in the comments

2021-11-26 17:07 UTC, ostatni5 commented on src/services/AuthService.tsx
> +	const [refreshInterval, setRefreshInterval] = useState(1000 * 60 * 3);
Well, I think that value is more readable as 3 mins than 180000.

2021-11-26 17:08 UTC, ostatni5 commented on src/services/AuthService.tsx
> +	const [refreshInterval, setRefreshInterval] = useState(1000 * 60 * 3);
It is overrated by backend response anyway, so it is not so important.

2021-11-26 19:17 UTC, Derstilon commented on src/services/AuthService.tsx
> +	const [refreshInterval, setRefreshInterval] = useState(1000 * 60 * 3);
Ok numbers can be left the way they are now. Just add simple comment explaining the numbers. Something like `// default refresh interval: 3 min`

2021-11-26 19:20 UTC, Derstilon commented on src/services/AuthService.tsx
> +const save = (key: string, value: any) => {
```suggestion
const save = (key: string, value: unknown) => {
```

2021-11-29 11:09 UTC, ostatni5 commented on src/services/AuthService.tsx
> +	login: (username: string, password: string) => void;
Yes, we are using username and password to authorize.

2021-11-29 11:28 UTC, Derstilon commented on src/WrapperApp/components/LoginPanel.tsx
> +	const [email, setEmail] = useState('');
```suggestion
	const [username, setUsername] = useState('');
```

2021-11-29 11:28 UTC, Derstilon commented on src/WrapperApp/components/LoginPanel.tsx
> +				<Button variant='outlined' onClick={() => login(email, password)}>
```suggestion
				<Button variant='outlined' onClick={() => login(username, password)}>
```

2021-11-29 11:28 UTC, Derstilon commented on src/WrapperApp/components/LoginPanel.tsx
>  		setEmail(event.target.value);
```suggestion
	const handleUsernameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
		setUsername(event.target.value);
```

2021-11-29 12:06 UTC, Derstilon approved these changes
Good job!

2021-11-29 12:23 UTC, merged