793 configure simulation run
yaptide/ui pull request #920
Opened 2023-04-14 16:59 UTC by Derstilon

![image](https://user-images.githubusercontent.com/26445545/232109515-443decba-a583-4b95-b94a-d4a27683f17f.png)
![image](https://user-images.githubusercontent.com/26445545/232109529-3e624116-e102-48e9-a0a1-c6228f902861.png)

2023-04-17 08:52 UTC, grzanka commented
@Derstilon does it make sense to test it now ?

2023-04-18 17:10 UTC, grzanka submitted a review, later dismissed
ok

2023-04-18 20:10 UTC, ostatni5 requested changes
Ok but it could be better
![image](https://media.tenor.com/fFntTHJYFPMAAAAM/random.gif)

2023-04-18 20:10 UTC, ostatni5 commented on src/services/ShSimulatorService.tsx
>  				console.log('postJob', endPoint, ntasks, simType, title, batchOptions, signal);
```suggestion
```

2023-04-18 21:03 UTC, grzanka commented on src/WrapperApp/components/Simulation/BatchParametersEditor.tsx
> +] as const;
`--time=0:15:00`

2023-04-18 21:08 UTC, grzanka commented on src/WrapperApp/components/Simulation/BatchParametersEditor.tsx
> +] as const;
That one should be enough for the beginning

2023-04-19 17:45 UTC, Derstilon commented on src/WrapperApp/components/Simulation/RunSimulationForm.tsx
How about now?

2023-04-20 08:38 UTC, ostatni5 approved these changes

2023-04-20 08:42 UTC, merged